"""
Django settings for tvt project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
from decouple import AutoConfig, Csv
import os
import pymysql
pymysql.install_as_MySQLdb()
from django.utils.translation import gettext_lazy as _


def config_bool(value):
    normalized = str(value).strip().lower()
    if normalized in {'1', 'true', 'yes', 'on'}:
        return True
    if normalized in {'0', 'false', 'no', 'off', 'release', 'production'}:
        return False
    raise ValueError(f"Invalid boolean value: {value}")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
file_config = AutoConfig(search_path=BASE_DIR)

# ENVIRONMENT resolution:
# - In production we expect ENVIRONMENT from process env (DirectAdmin/Passenger).
# - In development/testing .env at project root is supported for convenience.
ENVIRONMENT = os.environ.get('ENVIRONMENT')
if ENVIRONMENT is None:
    ENVIRONMENT = file_config('ENVIRONMENT', default='development', cast=str)
ENVIRONMENT = ENVIRONMENT.strip().lower()

_UNSET = object()


def config(name, default=_UNSET, cast=str):
    """
    Unified config accessor.
    - production: only reads process environment variables.
    - development/testing: reads env variables with .env fallback via decouple.
    """
    if ENVIRONMENT == 'production':
        raw = os.environ.get(name)
        if raw is None:
            if default is _UNSET:
                raise ValueError(f"Missing required environment variable: {name}")
            return cast(default) if cast is not None else default
        return cast(raw) if cast is not None else raw

    if default is _UNSET:
        return file_config(name, cast=cast)
    return file_config(name, default=default, cast=cast)


LOG_LEVEL_ORDER = {
    'basic': 1,
    'medium': 2,
    'verbose': 3,
}
ENV_LOG_LEVEL = {
    'production': 'basic',
    'testing': 'medium',
    'development': 'verbose',
}
SETTINGS_LOG_LEVEL = ENV_LOG_LEVEL.get(ENVIRONMENT, 'basic')
CONFIG_SOURCE_LABEL = (
    'system environment / DirectAdmin'
    if ENVIRONMENT == 'production'
    else '.env (with environment variable overrides)'
)


def _should_log(level):
    return LOG_LEVEL_ORDER[level] <= LOG_LEVEL_ORDER[SETTINGS_LOG_LEVEL]


def log_setting(name, value, level='basic', mask=False):
    if not _should_log(level):
        return
    safe_value = '***' if mask else value
    print(f"[SETTINGS] {name}: {safe_value}")


def config_csv(value):
    if isinstance(value, (list, tuple)):
        return [str(item).strip() for item in value if str(item).strip()]
    return [item.strip() for item in str(value).split(',') if item.strip()]


ADMIN_NAME = config('ADMIN_NAME', default='Tavata')
ADMIN_EMAIL = config('ADMIN_EMAIL', default='tavata.art@outlook.com')
ADMINS = [(ADMIN_NAME, ADMIN_EMAIL)]
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='').strip()
GOOGLE_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET', default='').strip()
GOOGLE_AUTH_ENABLED = bool(GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# 1. Leer la variable de entorno principal desde BASE_DIR/.env.
#    En Passenger el working directory puede variar, por eso fijamos search_path.
if ENVIRONMENT not in {'development', 'testing', 'production'}:
    raise ValueError(
        "ENVIRONMENT must be one of: development, testing, production"
    )

# 2. Configurar otras variables basadas en el ambiente
if ENVIRONMENT == 'development':
    SECRET_KEY = config('SECRET_KEY', default='django-insecure-dev-key-default')
    DEBUG = True
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())
    EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
elif ENVIRONMENT == 'testing':
    SECRET_KEY = config('SECRET_KEY', default='django-insecure-testing-key-default')
    DEBUG = config('DEBUG', default=False, cast=config_bool)
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost,testserver', cast=Csv())
    EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.locmem.EmailBackend')
else:  # production
    SECRET_KEY = config('SECRET_KEY')
    DEBUG = False
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())  # -> Permite múltiples hosts separados por comas
    EMAIL_BACKEND = config('EMAIL_BACKEND')
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='',
    cast=config_csv,
)

# Application definition

INSTALLED_APPS = [
    # 1. Las apps de Django Core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',

    # 2. Otras apps de Terceros
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'django_summernote',
    'tinymce',
    'solo',
    'mptt',
    'parler',

    # 3. Nuestras Propias Aplicaciones
    'core.apps.CoreConfig',
    'pages.apps.PagesConfig',
    'menus.apps.MenusConfig', 
    'site_settings.apps.SiteSettingsConfig', 
    'search.apps.SearchConfig', 
    'contact.apps.ContactConfig',
    'widgets.apps.WidgetsConfig',
    'accounts.apps.AccountsConfig',
    'categories.apps.CategoriesConfig',
    'gallery.apps.GalleryConfig',
    'testimonials',
    'posts',
    'tags',
    'comments.apps.CommentsConfig',
    'publications',
    'books.apps.BooksConfig',
    'notebooks.apps.NotebooksConfig',
    'shop.apps.ShopConfig',
    'fans.apps.FansConfig',
    'social.apps.SocialConfig',
    'ai_engine',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # <-- ¡Localization!
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tvt.urls'

# Instagram / Meta webhook and local AI. These values are defined in .env for
# development and in the hosting environment for production.
META_VERIFY_TOKEN = config('META_VERIFY_TOKEN', default='').strip()
META_APP_SECRET = config('META_APP_SECRET', default='').strip()
INSTAGRAM_USER_ID = config('INSTAGRAM_USER_ID', default='').strip()
INSTAGRAM_USER_ACCESS_TOKEN = config('INSTAGRAM_USER_ACCESS_TOKEN', default='').strip()
INSTAGRAM_API_VERSION = config('INSTAGRAM_API_VERSION', default='v26.0').strip()
INSTAGRAM_AUTO_REPLY_ENABLED = config(
    'INSTAGRAM_AUTO_REPLY_ENABLED', default=False, cast=config_bool
)
INSTAGRAM_AUTO_DRAFT_COMMENTS_ENABLED = config(
    'INSTAGRAM_AUTO_DRAFT_COMMENTS_ENABLED', default=False, cast=config_bool
)
INSTAGRAM_AUTO_DRAFT_MESSAGES_ENABLED = config(
    'INSTAGRAM_AUTO_DRAFT_MESSAGES_ENABLED', default=False, cast=config_bool
)
INSTAGRAM_AUTO_REPLY_MESSAGES_ENABLED = config(
    'INSTAGRAM_AUTO_REPLY_MESSAGES_ENABLED', default=False, cast=config_bool
)
USE_LLAMA = config('USAR_LLAMA_SINO_OPENAI', default=False, cast=config_bool)
LLAMA_BASE_URL = config('LLAMA_BASE_URL', default='http://127.0.0.1:11434').rstrip('/')
LLAMA_MODEL = config('LLAMA_MODEL', default='gemma3:4b').strip()

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'tvt.context_processors.languages_context',
                'tvt.context_processors.social_auth_context',
                'tvt.context_processors.cart_context',
                'tvt.context_processors.notifications_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'tvt.wsgi.application'
SITE_ID = config('SITE_ID', default=1, cast=int)

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = config('LOGIN_REDIRECT_URL', default='/')
ACCOUNT_LOGIN_METHODS = set(config('ACCOUNT_LOGIN_METHODS', default='username,email', cast=Csv()))
ACCOUNT_SIGNUP_FIELDS = config('ACCOUNT_SIGNUP_FIELDS', default='email,username*,password1*,password2*', cast=Csv())
ACCOUNT_EMAIL_VERIFICATION = config('ACCOUNT_EMAIL_VERIFICATION', default='optional')
SOCIALACCOUNT_AUTO_SIGNUP = config('SOCIALACCOUNT_AUTO_SIGNUP', default=True, cast=config_bool)
SOCIALACCOUNT_EMAIL_AUTHENTICATION = config('SOCIALACCOUNT_EMAIL_AUTHENTICATION', default=False, cast=config_bool)
SOCIALACCOUNT_GOOGLE_ACCESS_TYPE = config('SOCIALACCOUNT_GOOGLE_ACCESS_TYPE', default='online')
SOCIALACCOUNT_GOOGLE_PKCE_ENABLED = config('SOCIALACCOUNT_GOOGLE_PKCE_ENABLED', default=True, cast=config_bool)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': SOCIALACCOUNT_GOOGLE_ACCESS_TYPE,
        },
        'OAUTH_PKCE_ENABLED': SOCIALACCOUNT_GOOGLE_PKCE_ENABLED,
        'APPS': [
            {
                'client_id': GOOGLE_CLIENT_ID,
                'secret': GOOGLE_CLIENT_SECRET,
                'key': '',
            }
        ] if GOOGLE_AUTH_ENABLED else [],
    }
}

TINYMCE_DEFAULT_CONFIG = {
    'height': 500,
    'width': '100%',
    'menubar': 'file edit view insert format tools table help',
    'plugins': 'advlist autolink lists link image charmap print preview anchor '
               'searchreplace visualblocks code fullscreen '
               'insertdatetime media table paste code help wordcount',
    'toolbar': 'undo redo | formatselect | bold italic backcolor | '
               'alignleft aligncenter alignright alignjustify | '
               'bullist numlist outdent indent | removeformat | help',
    'branding': False,
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

MYSQL_ENGINES = {'django.db.backends.mysql'}


def _is_path_like_db_name(value):
    value = str(value or '')
    return '/' in value or '\\' in value or value.endswith('.sqlite3')


def build_mysql_database_from_env(engine='django.db.backends.mysql'):
    database_config = {
        'ENGINE': engine,
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        }
    }
    test_db_name = config('DB_TEST_NAME', default='').strip()
    if test_db_name:
        database_config['TEST'] = {'NAME': test_db_name}
    return database_config

if ENVIRONMENT == 'production':
    # Production behavior remains environment-driven (DirectAdmin/session variables).
    DATABASES = {'default': build_mysql_database_from_env()}
elif ENVIRONMENT == 'testing':  # .env-driven test configuration
    test_db_engine = config('DB_ENGINE', default='').strip()
    if not test_db_engine:
        raise ValueError(
            "Invalid testing database configuration: DB_ENGINE is required when "
            "ENVIRONMENT=testing. Example: DB_ENGINE=django.db.backends.mysql"
        )
    if test_db_engine not in MYSQL_ENGINES:
        raise ValueError(
            "Invalid testing database configuration: only MySQL/MariaDB is allowed "
            "in testing. Use DB_ENGINE=django.db.backends.mysql"
        )

    test_db_name = config('DB_NAME')
    if _is_path_like_db_name(test_db_name):
        raise ValueError(
            "Invalid testing database configuration: DB_NAME looks like a file path. "
            "For MySQL/MariaDB it must be a database schema name, e.g. 'tvtavata_tvt'."
        )

    DATABASES = {'default': build_mysql_database_from_env(engine=test_db_engine)}
else:  # development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# MariaDB does not support conditional unique constraints.
# django-allauth's account.EmailAddress declares two partial unique constraints
# for primary/verified email integrity, but the same business rules are still
# enforced in application code by allauth. We silence this backend-specific
# warning to keep checks and migrations clean on MySQL/MariaDB environments.
SILENCED_SYSTEM_CHECKS = []
if DATABASES['default'].get('ENGINE') in MYSQL_ENGINES:
    SILENCED_SYSTEM_CHECKS.append('models.W036')


def summarize_database(database_config):
    engine = database_config.get('ENGINE', '')
    if engine == 'django.db.backends.sqlite3':
        return f"SQLite ({database_config.get('NAME')})"
    return (
        f"{engine} "
        f"(name={database_config.get('NAME')}, "
        f"host={database_config.get('HOST', '')}, "
        f"port={database_config.get('PORT', '')})"
    )


# --- CACHING CONFIGURATION ---
# https://docs.djangoproject.com/en/5.2/topics/cache/
CACHE_BACKEND = config(
    'CACHE_BACKEND',
    default='django.core.cache.backends.locmem.LocMemCache',
).strip()
CACHE_LOCATION = config(
    'CACHE_LOCATION',
    default='tavata-cms-unique-cache',
).strip()
CACHE_TIMEOUT = config('CACHE_TIMEOUT', default=300, cast=int)
CACHE_LOG_LEVEL = config('CACHE_LOG_LEVEL', default='INFO').strip().upper()
COMMENT_TRANSLATION_PROVIDER = config(
    'COMMENT_TRANSLATION_PROVIDER',
    default='disabled',
).strip().lower()
COMMENT_TRANSLATION_TIMEOUT = config(
    'COMMENT_TRANSLATION_TIMEOUT',
    default=10,
    cast=int,
)
DEEPL_API_KEY = config('DEEPL_API_KEY', default='').strip()
DEEPL_API_URL = config(
    'DEEPL_API_URL',
    default='https://api-free.deepl.com/v2/translate',
).strip()
ALLOW_PRODUCTION_LOCMEM_CACHE = config(
    'ALLOW_PRODUCTION_LOCMEM_CACHE',
    default=False,
    cast=config_bool,
)

if ENVIRONMENT == 'production':
    if EMAIL_BACKEND == 'django.core.mail.backends.console.EmailBackend':
        raise ValueError(
            "Invalid production configuration: EMAIL_BACKEND must not use the console backend."
        )
    if (
        CACHE_BACKEND == 'django.core.cache.backends.locmem.LocMemCache'
        and not ALLOW_PRODUCTION_LOCMEM_CACHE
    ):
        raise ValueError(
            "Invalid production configuration: LocMemCache is only allowed when "
            "ALLOW_PRODUCTION_LOCMEM_CACHE=True is set explicitly as a temporary exception."
        )

CACHES = {
    'default': {
        'BACKEND': CACHE_BACKEND,
        'LOCATION': CACHE_LOCATION,
        'TIMEOUT': CACHE_TIMEOUT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Idioma por defecto
LANGUAGE_CODE = config('LANGUAGE_CODE', default='en')

# Lista de idiomas disponibles
LANGUAGES = [
    ('es', _('Español')),
    ('en', _('English')),
    ('ca', _('Català')),
]

PARLER_LANGUAGE_OPTIONS = (
    {'code': 'es'},
    {'code': 'en'},
    {'code': 'ca'},
)

PARLER_LANGUAGES = {
    None: PARLER_LANGUAGE_OPTIONS,
    SITE_ID: PARLER_LANGUAGE_OPTIONS,
    'default': {
        'fallbacks': ['es'],
        'hide_untranslated': False,
        'redirect_on_fallback': False,
    }
}
PARLER_ENABLE_CACHING = config('PARLER_ENABLE_CACHING', default=False, cast=config_bool)

# Rutas donde Django buscará los archivos de traducción (.po/.mo)
LOCALE_PATHS = [
    BASE_DIR / 'locale/',
]

TIME_ZONE = config('TIME_ZONE', default='UTC')

USE_I18N = config('USE_I18N', default=True, cast=config_bool)

USE_TZ = config('USE_TZ', default=True, cast=config_bool)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = config('STATIC_URL', default='/static/')

# La ruta donde `collectstatic` copiará todos los archivos para producción.
# Es bueno tenerla definida aunque en desarrollo no se use directamente.
if ENVIRONMENT == 'production':
    STATIC_ROOT = config('STATIC_ROOT')
else:
    STATIC_ROOT = config('STATIC_ROOT', default=str(BASE_DIR / 'staticfiles'))

# ¡LA CONFIGURACIÓN CLAVE PARA DESARROLLO!
# Directorios adicionales donde el servidor de desarrollo de Django buscará archivos estáticos.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if ENVIRONMENT == 'production':
    MEDIA_URL = config('MEDIA_URL', default='/media/')
    MEDIA_ROOT = config('MEDIA_ROOT')
else:
    MEDIA_URL = config('MEDIA_URL', default='/media/')
    MEDIA_ROOT = config('MEDIA_ROOT', default=str(BASE_DIR / 'media'))

# Security defaults per environment (DirectAdmin/Passenger friendly).
if ENVIRONMENT == 'production':
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=config_bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=config_bool)
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=config_bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=config_bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=config_bool)
    SECURE_PROXY_SSL_HEADER_ENABLED = config('SECURE_PROXY_SSL_HEADER_ENABLED', default=False, cast=config_bool)
    if SECURE_PROXY_SSL_HEADER_ENABLED:
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# ------------------------------------------------------------------------------
# SETTINGS INITIALIZATION LOGS (safe, environment-aware)
# ------------------------------------------------------------------------------
log_setting('Environment', ENVIRONMENT, level='basic')
log_setting('DEBUG', DEBUG, level='basic')
log_setting('Configuration source', CONFIG_SOURCE_LABEL, level='basic')
log_setting('Database', summarize_database(DATABASES.get('default', {})), level='basic')
log_setting('STATIC_URL', STATIC_URL, level='medium')
log_setting('STATIC_ROOT', STATIC_ROOT, level='medium')
log_setting('MEDIA_URL', MEDIA_URL, level='medium')
log_setting('MEDIA_ROOT', MEDIA_ROOT, level='medium')
log_setting('ALLOWED_HOSTS', ALLOWED_HOSTS, level='medium')
log_setting('CSRF_TRUSTED_ORIGINS', CSRF_TRUSTED_ORIGINS, level='medium')
log_setting('Log verbosity profile', SETTINGS_LOG_LEVEL, level='verbose')
log_setting('Database engine', DATABASES['default'].get('ENGINE', ''), level='verbose')
log_setting('Database host', DATABASES['default'].get('HOST', ''), level='verbose')
log_setting('Database port', DATABASES['default'].get('PORT', ''), level='verbose')
log_setting('Cache backend', CACHE_BACKEND, level='medium')
log_setting('Cache location', CACHE_LOCATION, level='verbose')
log_setting('Cache default timeout', CACHE_TIMEOUT, level='verbose')

X_FRAME_OPTIONS = config('X_FRAME_OPTIONS', default='SAMEORIGIN')

# ==============================================================================
# LOGGING CONFIGURATION
# ==============================================================================

LOG_FILE_PATH = Path(config('LOG_FILE_PATH', default=BASE_DIR.parent / 'tvtlogs/error.log'))
LOG_FILE_PATH.parent.mkdir(parents=True, exist_ok=True)

BOOTSTRAP_SUPERUSER_ENABLED = config(
    'BOOTSTRAP_SUPERUSER_ENABLED',
    default=False,
    cast=config_bool,
)
BOOTSTRAP_SUPERUSER_TOKEN = config('BOOTSTRAP_SUPERUSER_TOKEN', default='')
BOOTSTRAP_SUPERUSER_USERNAME = config('BOOTSTRAP_SUPERUSER_USERNAME', default='admin')
BOOTSTRAP_SUPERUSER_EMAIL = config('BOOTSTRAP_SUPERUSER_EMAIL', default='')
BOOTSTRAP_SUPERUSER_PASSWORD = config('BOOTSTRAP_SUPERUSER_PASSWORD', default='')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False, # No desactiva los loggers por defecto de Django

    # --- FORMATTERS: Cómo se verá cada línea del log ---
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },

    # --- FILTERS: Para añadir contexto o filtrar logs ---
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },

    # --- HANDLERS: A dónde se envía cada log (consola, archivo, email) ---
    'handlers': {
        # Handler para la consola de desarrollo
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'], # Solo funciona si DEBUG=True
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        # Handler para guardar en un archivo los warnings y errores
        'file_error': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_FILE_PATH,
            'maxBytes': config('LOG_FILE_MAX_BYTES', default=1024 * 1024 * 5, cast=int),
            'backupCount': config('LOG_FILE_BACKUP_COUNT', default=2, cast=int),
            'formatter': 'verbose',
        },
        # Handler para que los administradores reciban un email en caso de error 500
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'], # Solo funciona si DEBUG=False
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },

    # --- LOGGERS: El cerebro que une todo ---
    'loggers': {
        # Logger principal de Django. Capturará todo lo que pase en el framework.
        'django': {
            'handlers': ['console', 'file_error', 'mail_admins'],
            'level': 'INFO',
            'propagate': True,
        },
        'cache': {
            'handlers': ['console', 'file_error'],
            'level': CACHE_LOG_LEVEL,
            'propagate': False,
        },
        # Podemos crear loggers para nuestras propias apps si queremos
        # 'blog': {
        #     'handlers': ['console', 'file_error'],
        #     'level': 'DEBUG',
        # },
    },
}

# URL to redirect to after a successful logout.
LOGOUT_REDIRECT_URL = config('LOGOUT_REDIRECT_URL', default='/')
