# Generated by Django 5.2.13 on 2026-05-10 14:58

import django.db.models.deletion
import django.utils.timezone
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Daily View Count')),
            ],
            options={
                'verbose_name': 'Post Daily Metric',
                'verbose_name_plural': 'Post Daily Metrics',
            },
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
                ('summary', models.CharField(blank=True, help_text='Short text used as the social sharing description.', max_length=280, verbose_name='Summary')),
                ('content', models.TextField(verbose_name='Content')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'Post Translation',
                'db_table': 'posts_post_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('editor_rating', models.PositiveIntegerField(default=0, help_text='A score from 0-100. Higher numbers can be used for ordering or editor’s picks.', verbose_name="Editor's Rating")),
                ('show_in_post_grids', models.BooleanField(db_index=True, default=True, help_text='Controls whether this post can appear in homepage/category grid widgets.', verbose_name='Show in Post Grids')),
                ('migrated', models.BooleanField(db_index=True, default=False, help_text='Internal admin flag used to avoid exporting or importing this post more than once.', verbose_name='Migrated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('categories', models.ManyToManyField(blank=True, related_name='posts_posts', to='categories.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_date'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
