# Generated by Django 5.2.13 on 2026-05-10 14:58

import django.db.models.deletion
import parler.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        ('posts', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags assigned to this post. Managed via TaggedPost intermediate model.', related_name='posts', through='tags.TaggedPost', to='tags.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='postdailymetric',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='posts.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='featured_image_asset',
            field=models.ForeignKey(blank=True, help_text='Optional gallery row for the featured image; overrides the upload below when set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Featured image (library)'),
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='posts.post'),
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='social_image_asset',
            field=models.ForeignKey(blank=True, help_text='Optional gallery row for the square social image; overrides the upload below when set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Social image (library)'),
        ),
        migrations.AddIndex(
            model_name='postdailymetric',
            index=models.Index(fields=['date'], name='posts_postd_date_4eb997_idx'),
        ),
        migrations.AddIndex(
            model_name='postdailymetric',
            index=models.Index(fields=['post', 'date'], name='posts_postd_post_id_93248e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postdailymetric',
            unique_together={('post', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='posttranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
