# Generated by Django 5.2.13 on 2026-05-11 01:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPointAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Points')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_allocations', to='posts.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_point_allocations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Post point allocation',
                'verbose_name_plural': 'Post point allocations',
                'indexes': [models.Index(fields=['date'], name='posts_postp_date_585260_idx'), models.Index(fields=['post', 'date'], name='posts_postp_post_id_87d323_idx'), models.Index(fields=['user', 'date'], name='posts_postp_user_id_fce683_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post', 'date'), name='unique_post_point_allocation_per_day')],
            },
        ),
    ]
