# Generated by Django 5.2.13 on 2026-05-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_postpointallocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("post", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="favorites", to="posts.post", verbose_name="Post")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="post_favorites", to="auth.user", verbose_name="User")),
            ],
            options={
                "verbose_name": "Post favorite",
                "verbose_name_plural": "Post favorites",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="postfavorite",
            constraint=models.UniqueConstraint(fields=("user", "post"), name="unique_post_favorite"),
        ),
        migrations.AddIndex(
            model_name="postfavorite",
            index=models.Index(fields=["user", "created_at"], name="posts_postf_user_id_f49742_idx"),
        ),
        migrations.AddIndex(
            model_name="postfavorite",
            index=models.Index(fields=["post", "created_at"], name="posts_postf_post_id_096eb2_idx"),
        ),
    ]
