# Generated by Codex on 2026-05-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        ("posts", "0004_postfavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="posttranslation",
            name="mobile_image_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional gallery row for a vertical 9:16 image used in mobile-first widgets.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="gallery.image",
                verbose_name="Mobile image (library)",
            ),
        ),
    ]
