# Generated by Django 5.2.13 on 2026-09-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_postcontentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontentblock',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Describe the image. If empty, the section title or post title is used.', max_length=250, verbose_name='Image alternative text'),
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Describe the image. If empty, the post title is used.', max_length=250, verbose_name='Featured image alternative text'),
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='mobile_image_alt',
            field=models.CharField(blank=True, help_text='Describe the image. If empty, the post title is used.', max_length=250, verbose_name='Mobile image alternative text'),
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='social_image_alt',
            field=models.CharField(blank=True, help_text='Describe the image. If empty, the post title is used.', max_length=250, verbose_name='Social image alternative text'),
        ),
    ]
