# Generated by Django 5.2.13 on 2026-09-10 22:24

from django.db import migrations, models


def populate_short_codes(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    for post in Post.objects.filter(short_code__isnull=True).iterator():
        Post.objects.filter(pk=post.pk).update(short_code=f"p-{post.pk}")


def clear_short_codes(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    Post.objects.filter(short_code__startswith="p-").update(short_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_postcontentblock_image_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_code',
            field=models.SlugField(blank=True, editable=False, max_length=32, null=True, unique=True, verbose_name='Short link code'),
        ),
        migrations.RunPython(populate_short_codes, clear_short_codes),
    ]
