# Generated by Django 5.2.13 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0024_post_short_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcontentblock",
            name="show_in_listings",
            field=models.BooleanField(
                default=False,
                help_text="Show this complete visual section as a mini-post in latest entries and search results.",
                verbose_name="Show in listings and search",
            ),
        ),
    ]
