# Generated by Django 5.2.13 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0025_postcontentblock_show_in_listings"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcontentblock",
            name="summary",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Brief, self-contained summary used before the section content and in "
                    "search and listing cards. Recommended: 140–160 characters."
                ),
                max_length=160,
                verbose_name="Mini-post summary (SEO)",
            ),
        ),
    ]
