# Generated by Django 5.2.13 on 2026-09-13

from html import unescape
import re

from django.db import migrations, models


CUSTOM_SUMMARIES = {
    "Ocho trabajadores y nadie dedicado exclusivamente a la prevención": (
        "En un restaurante, un suelo resbaladizo compite con urgencias, mantenimiento "
        "y prevención. El caso muestra cómo convertir un aviso en una actuación trazable."
    ),
    "El caso del autónomo, Cuando prevenir también significa detener el trabajo": (
        "Un autónomo detecta una escalera insegura en el centro del cliente. El caso "
        "explica cómo detener el trabajo, comunicar el riesgo y registrar responsabilidades."
    ),
    "Dos casos que no deben confundirse, pyme y autónomo": (
        "Pyme y autónomo comparten retos preventivos, pero sus responsabilidades y "
        "recursos difieren. Compararlos ayuda a diseñar apoyos útiles y proporcionados."
    ),
}


def _plain_text(value):
    value = re.sub(r"<[^>]+>", " ", value or "")
    return " ".join(unescape(value).split())


def _fallback_summary(block):
    text = _plain_text(block.content)
    if text:
        # A concise extraction is preferable to creating an empty SEO field
        # for historical content whose heading was not descriptive enough.
        return text[:160].rstrip(" ,;:-")
    heading = (block.heading or "").strip()
    return heading[:160] or "Contenido pendiente de resumen."


def fill_content_block_summaries(apps, schema_editor):
    PostContentBlock = apps.get_model("posts", "PostContentBlock")
    for block in PostContentBlock.objects.filter(block_type="content", summary=""):
        block.summary = CUSTOM_SUMMARIES.get(block.heading, _fallback_summary(block))
        block.save(update_fields=["summary"])


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0026_postcontentblock_summary"),
    ]

    operations = [
        migrations.RunPython(fill_content_block_summaries, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="postcontentblock",
            constraint=models.CheckConstraint(
                condition=models.Q(block_type="related_post") | ~models.Q(summary=""),
                name="post_content_block_content_summary_required",
            ),
        ),
    ]
