# Generated by Django 5.2.13 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0027_fill_content_block_summaries_and_require_them"),
    ]

    operations = [
        migrations.AddField(
            model_name="posttranslation",
            name="conclusions",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Optional closing content shown after all mini-posts. Use it for a "
                    "conclusion, synthesis, open question, or next step."
                ),
                verbose_name="Conclusions",
            ),
        ),
    ]
