# Generated by Django 5.2.13 on 2026-09-17 18:18

import secrets

from django.db import migrations, models
from django.utils.text import slugify


ALPHABET = "abcdefghijkmnopqrstuvwxyz23456789"


def _new_code(Post, PostContentBlock):
    while True:
        code = "".join(secrets.choice(ALPHABET) for _ in range(8))
        if not Post.objects.filter(short_code=code).exists() and not PostContentBlock.objects.filter(short_code=code).exists():
            return code


def seed_public_mini_post_urls(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    PostContentBlock = apps.get_model("posts", "PostContentBlock")

    # Replace the temporary predictable p-<id> codes with permanent opaque ones.
    for post in Post.objects.filter(models.Q(short_code__isnull=True) | models.Q(short_code="") | models.Q(short_code__startswith="p-")).iterator():
        Post.objects.filter(pk=post.pk).update(short_code=_new_code(Post, PostContentBlock))

    used_slugs = set(
        PostContentBlock.objects.exclude(share_slug="").values_list("post_id", "language", "share_slug")
    )
    blocks = PostContentBlock.objects.filter(
        block_type="content",
        heading__gt="",
        summary__gt="",
        content__gt="",
        image_asset__isnull=False,
    ).iterator()
    for block in blocks:
        share_slug = block.share_slug
        if not share_slug:
            base = (block.anchor or slugify(block.heading) or f"section-{block.pk}")[:120]
            share_slug = base
            suffix = 2
            while (block.post_id, block.language, share_slug) in used_slugs:
                suffix_text = f"-{suffix}"
                share_slug = f"{base[:120 - len(suffix_text)]}{suffix_text}"
                suffix += 1
            used_slugs.add((block.post_id, block.language, share_slug))

        updates = {"share_slug": share_slug}
        if not block.short_code:
            updates["short_code"] = _new_code(Post, PostContentBlock)
        PostContentBlock.objects.filter(pk=block.pk).update(**updates)


def reverse_seed_public_mini_post_urls(apps, schema_editor):
    # URLs are intentionally permanent once generated; reversing a schema
    # migration must not erase links that may already have been shared.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_posttranslation_conclusions'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontentblock',
            name='share_slug',
            field=models.SlugField(blank=True, editable=False, help_text='Stable public slug generated when this mini-post is first saved.', max_length=120, verbose_name='Public mini-post slug'),
        ),
        migrations.AddField(
            model_name='postcontentblock',
            name='short_code',
            field=models.SlugField(blank=True, editable=False, max_length=32, null=True, unique=True, verbose_name='Short link code'),
        ),
        migrations.RunPython(seed_public_mini_post_urls, reverse_seed_public_mini_post_urls),
    ]
