# Generated by Django 5.2.13 on 2026-05-10 14:58

import django.db.models.deletion
import gallery.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Used as the filename stem: gallery/{slug}.ext', max_length=100, unique=True, verbose_name='Slug')),
                ('language', models.CharField(choices=[('es', 'es'), ('en', 'en'), ('ca', 'ca')], default='es', max_length=7, verbose_name='Language')),
                ('image', models.ImageField(blank=True, null=True, upload_to=gallery.models.gallery_image_upload_to, verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Summary / Abstract')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('derived_from', models.ForeignKey(blank=True, help_text='Optional source image when this row was created as a new version.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='gallery.image', verbose_name='Derived from')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StagedUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=gallery.models.staged_upload_to, verbose_name='Staged file')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_staged_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staged upload',
                'verbose_name_plural': 'Staged uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
