# Generated by Django 5.2.13 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagedupload",
            name="convert_to_webp",
            field=models.BooleanField(default=True),
        ),
    ]
