# Generated by Django 5.2.13 on 2026-09-09 18:47

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_stagedupload_convert_to_webp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=gallery.models.gallery_image_upload_to, verbose_name='Image'),
        ),
    ]
