# Generated by Django 5.2.13 on 2026-05-10 14:58

import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=32, verbose_name='ISBN')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, verbose_name='Publication Date')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published?')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Currency')),
                ('allow_free_preview', models.BooleanField(default=True, verbose_name='Allow Free Preview')),
                ('requires_purchase', models.BooleanField(default=False, verbose_name='Requires Purchase')),
                ('available_from', models.DateField(blank=True, help_text='Optional release date for the purchasable full edition.', null=True, verbose_name='Available from')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('authors', models.ManyToManyField(related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Authors')),
                ('categories', models.ManyToManyField(blank=True, related_name='books', to='categories.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-publication_date', '-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BookTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtitle')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Description')),
                ('excerpt', tinymce.models.HTMLField(blank=True, verbose_name='Excerpt')),
                ('table_of_contents', tinymce.models.HTMLField(blank=True, verbose_name='Table of contents')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
                ('preview_pdf', models.FileField(blank=True, null=True, upload_to='books/previews/', verbose_name='Preview PDF')),
                ('full_pdf', models.FileField(blank=True, null=True, upload_to='books/files/', verbose_name='Full PDF')),
                ('cover_image_asset', models.ForeignKey(blank=True, help_text='Primary book cover from Media Library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Cover image (library)')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='books.book')),
                ('social_image_asset', models.ForeignKey(blank=True, help_text='Square or social-preview image from Media Library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Social image (library)')),
            ],
            options={
                'verbose_name': 'Book Translation',
                'db_table': 'books_book_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
