# Generated by Django 5.2.13 on 2026-05-25 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktranslation',
            name='mobile_image_asset',
            field=models.ForeignKey(blank=True, help_text='Vertical 9:16 image optimized for mobile layouts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Mobile image (library)'),
        ),
    ]
