# Generated by Django 5.2.13 on 2026-09-11 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_booktranslation_mobile_image_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_mode',
            field=models.CharField(choices=[('internal', 'Internal authors'), ('external', 'External authors')], default='internal', max_length=12, verbose_name='Author type'),
        ),
        migrations.AddField(
            model_name='book',
            name='direct_pdf_url',
            field=models.URLField(blank=True, help_text='Optional direct URL to the original PDF when it exists.', verbose_name='Direct PDF URL'),
        ),
        migrations.AddField(
            model_name='book',
            name='external_authors',
            field=models.TextField(blank=True, help_text='Use this field when the book was not written by TVTente users.', verbose_name='External authors'),
        ),
        migrations.AddField(
            model_name='book',
            name='official_source_url',
            field=models.URLField(blank=True, verbose_name='Official source URL'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Authors'),
        ),
    ]
