# Generated by Django 5.2.13 on 2026-05-10 14:58

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='Author Name')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Author Email')),
                ('content', models.TextField(verbose_name='Content')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Original Language')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved?')),
                ('translated_content', models.TextField(blank=True, null=True, verbose_name='Translated Content')),
                ('translation_language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Translation Language')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.comment', verbose_name='Parent Comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
