# Generated by Django 5.2.13 on 2026-05-10 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='translated_by',
            field=models.ForeignKey(blank=True, help_text='User who provided the translation, if different from the author.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_comments', to=settings.AUTH_USER_MODEL, verbose_name='Translated by'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_made_by', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
