# Generated by Django 5.2.13 on 2026-05-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_comment_translations(apps, schema_editor):
    Comment = apps.get_model("comments", "Comment")
    CommentTranslation = apps.get_model("comments", "CommentTranslation")

    translations_to_create = []
    for comment in Comment.objects.exclude(
        translated_content__isnull=True,
    ).exclude(
        translated_content="",
    ).exclude(
        translation_language__isnull=True,
    ).exclude(
        translation_language="",
    ):
        translations_to_create.append(
            CommentTranslation(
                comment_id=comment.pk,
                language=comment.translation_language,
                content=comment.translated_content,
                source="human",
                provider="",
                translated_by_id=comment.translated_by_id,
            )
        )

    if translations_to_create:
        CommentTranslation.objects.bulk_create(
            translations_to_create,
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language", models.CharField(max_length=10, verbose_name="Language")),
                ("content", models.TextField(verbose_name="Translated Content")),
                ("source", models.CharField(choices=[("human", "Human"), ("machine", "Machine")], default="human", max_length=16, verbose_name="Translation source")),
                ("provider", models.CharField(blank=True, help_text="Optional provider or engine name for machine translations.", max_length=64, verbose_name="Translation provider")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("comment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="translations", to="comments.comment", verbose_name="Comment")),
                ("translated_by", models.ForeignKey(blank=True, help_text="User who provided the translation, if different from the author.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="comment_translations", to=settings.AUTH_USER_MODEL, verbose_name="Translated by")),
            ],
            options={
                "verbose_name": "Comment translation",
                "verbose_name_plural": "Comment translations",
                "constraints": [models.UniqueConstraint(fields=("comment", "language"), name="unique_comment_translation_language")],
            },
        ),
        migrations.RunPython(
            migrate_legacy_comment_translations,
            migrations.RunPython.noop,
        ),
    ]
