# Generated by Django 5.2.13 on 2026-05-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_commenttranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttranslation',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Whether this translation is approved for public display.', verbose_name='Is approved?'),
        ),
        migrations.AddField(
            model_name='commenttranslation',
            name='is_preferred',
            field=models.BooleanField(default=False, help_text='Whether this translation should be shown before other alternatives for the same language.', verbose_name='Is preferred?'),
        ),
    ]
