# Generated by Django 5.2.13 on 2026-05-11 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_commenttranslation_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttranslation',
            name='pending_content',
            field=models.TextField(blank=True, null=True, verbose_name='Pending suggested content'),
        ),
        migrations.AddField(
            model_name='commenttranslation',
            name='pending_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pending suggested at'),
        ),
        migrations.AddField(
            model_name='commenttranslation',
            name='pending_translated_by',
            field=models.ForeignKey(blank=True, help_text='User who suggested a human translation pending moderation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_comment_translation_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Pending suggested by'),
        ),
    ]
