# Generated by Django 5.2.13 on 2026-05-10 14:58

import django.db.models.deletion
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('gallery', '0001_initial'),
        ('widgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('show_separator_after', models.BooleanField(default=True, help_text='Displays a separator after this section.', verbose_name='Show Separator After')),
                ('background_style', models.CharField(choices=[('default', 'Default'), ('muted', 'Muted'), ('notice', 'Notice'), ('surface', 'Surface')], default='default', max_length=20, verbose_name='Background Style')),
                ('full_width', models.BooleanField(default=False, help_text='If enabled, the section content can span the full content column width.', verbose_name='Full Width')),
                ('widget_zone', models.ForeignKey(blank=True, help_text='Optional widget zone rendered after this section content.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_sections', to='widgets.widgetzone', verbose_name='Widget Zone After Content')),
            ],
            options={
                'verbose_name': 'Home Section',
                'verbose_name_plural': 'Home Sections',
                'ordering': ('order', 'id'),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('is_homepage', models.BooleanField(default=False, help_text='Mark only one page with this option. If multiple are marked, the most recent one will be used.', verbose_name='Is Homepage?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('importance_order', models.PositiveIntegerField(default=99, help_text="A lower number means higher priority in search results. E.g., 1 for 'About Us', 2 for 'Contact', 99 for others.", verbose_name='Importance Order')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('categories', models.ManyToManyField(blank=True, related_name='pages', to='categories.category', verbose_name='Categories')),
                ('featured_image_asset', models.ForeignKey(blank=True, help_text='Optional gallery row for the unsuffixed featured_image column (usually default locale).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Featured image (library, default column)')),
                ('featured_image_asset_ca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Featured image (library, CA)')),
                ('featured_image_asset_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Featured image (library, EN)')),
                ('featured_image_asset_es', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Featured image (library, ES)')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomeSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(help_text='Internal name for organizing this home section in the admin.', max_length=160, verbose_name='Internal Title')),
                ('content', models.TextField(blank=True, help_text='Optional HTML/WYSIWYG content shown for this section.', verbose_name='Content')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.homesection')),
            ],
            options={
                'verbose_name': 'Home Section Translation',
                'db_table': 'pages_homesection_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug (URL friendly)')),
                ('content', models.TextField(verbose_name='Content')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)')),
                ('abstract', models.TextField(blank=True, verbose_name='Abstract')),
                ('keywords', models.CharField(blank=True, help_text='Optional comma-separated keywords.', max_length=300, verbose_name='Keywords')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.page')),
            ],
            options={
                'verbose_name': 'page Translation',
                'db_table': 'pages_page_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master'), ('language_code', 'slug')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
