# Generated by Codex on 2026-05-25

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        ("pages", "0001_initial"),
        ("widgets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("section_type", models.CharField(choices=[("content", "Content block"), ("widget_zone", "Widget zone"), ("hero", "Hero")], default="content", max_length=30, verbose_name="Section Type")),
                ("enabled", models.BooleanField(db_index=True, default=True, verbose_name="Enabled")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Display Order")),
                ("background_style", models.CharField(choices=[("default", "Default"), ("muted", "Muted"), ("notice", "Notice"), ("surface", "Surface"), ("dark", "Dark")], default="default", max_length=20, verbose_name="Background Style")),
                ("full_width", models.BooleanField(default=False, help_text="If enabled, the section content can span the full content column width.", verbose_name="Full Width")),
                ("show_separator_after", models.BooleanField(default=False, help_text="Displays a separator after this section.", verbose_name="Show Separator After")),
                ("background_image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="gallery.image", verbose_name="Background Image")),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="page_sections", to="pages.page", verbose_name="Page")),
                ("widget_zone", models.ForeignKey(blank=True, help_text="Optional widget zone rendered inside this page section.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="page_sections", to="widgets.widgetzone", verbose_name="Widget Zone")),
            ],
            options={
                "verbose_name": "Page Section",
                "verbose_name_plural": "Page Sections",
                "ordering": ("order", "id"),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PageSectionTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("internal_title", models.CharField(help_text="Internal name for organizing this page section in the admin.", max_length=160, verbose_name="Internal Title")),
                ("heading", models.CharField(blank=True, max_length=250, verbose_name="Visible Heading")),
                ("content", models.TextField(blank=True, help_text="Optional HTML/WYSIWYG content shown for this page section.", verbose_name="Content")),
                ("button_text", models.CharField(blank=True, max_length=120, verbose_name="Button Text")),
                ("button_url", models.CharField(blank=True, help_text="Optional internal or external URL for the section button.", max_length=300, verbose_name="Button URL")),
                ("master", parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="translations", to="pages.pagesection")),
            ],
            options={
                "verbose_name": "Page Section Translation",
                "db_table": "pages_pagesection_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
