# Generated by Codex on 2026-05-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_pagesection"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagesection",
            name="linked_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional page rendered inside this section when using the embedded page type.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="embedded_in_sections",
                to="pages.page",
                verbose_name="Linked Page",
            ),
        ),
        migrations.AlterField(
            model_name="pagesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("content", "Content block"),
                    ("widget_zone", "Widget zone"),
                    ("hero", "Hero"),
                    ("page", "Embedded page"),
                ],
                default="content",
                max_length=30,
                verbose_name="Section Type",
            ),
        ),
    ]
