# Generated by Codex on 2026-05-25

from django.db import migrations, models
from django.db.models import F, Q


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_pagesection_linked_page_and_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pagesection",
            index=models.Index(fields=["page", "order"], name="pages_pages_page_id_af72a7_idx"),
        ),
        migrations.AddConstraint(
            model_name="pagesection",
            constraint=models.CheckConstraint(
                condition=Q(section_type="page", linked_page__isnull=False)
                | ~Q(section_type="page"),
                name="pagesection_page_type_requires_linked_page",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagesection",
            constraint=models.CheckConstraint(
                condition=Q(section_type__in=["hero", "widget_zone"], widget_zone__isnull=False)
                | ~Q(section_type__in=["hero", "widget_zone"]),
                name="pagesection_widget_types_require_widget_zone",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagesection",
            constraint=models.CheckConstraint(
                condition=Q(linked_page__isnull=True) | ~Q(page=F("linked_page")),
                name="pagesection_linked_page_not_self",
            ),
        ),
    ]
