# Generated by Django 5.2.13 on 2026-05-25 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('gallery', '0001_initial'),
        ('pages', '0004_pagesection_integrity_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_homepage',
            field=models.BooleanField(default=False, help_text='Only one page can be the homepage. Saving this page as homepage will unset the previous one.', verbose_name='Is Homepage?'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(condition=models.Q(('is_homepage', True)), fields=('is_homepage',), name='unique_active_homepage'),
        ),
    ]
