# Generated by Codex on 2026-09-13

from django.db import migrations, models


PUBLICATION_SECTION_GROUPS = (
    "Researcher",
    "Reviewer",
    "Admin",
    "Site Manager",
)


def restrict_homepage_publications(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    PageSection = apps.get_model("pages", "PageSection")

    groups = list(Group.objects.filter(name__in=PUBLICATION_SECTION_GROUPS))
    if not groups:
        return

    for section in PageSection.objects.filter(widget_zone__slug="homepage-publications"):
        section.allowed_groups.set(groups)


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pages", "0005_alter_page_is_homepage_page_unique_active_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagesection",
            name="allowed_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to show this section to everyone. Select groups to restrict it to authenticated members.",
                related_name="visible_page_sections",
                to="auth.group",
                verbose_name="Visible for groups",
            ),
        ),
        migrations.RunPython(restrict_homepage_publications, migrations.RunPython.noop),
    ]
