# Generated by Django 5.2.13 on 2026-05-10 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent'), (5, 'Critical')], default=2, verbose_name='Priority')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates if an admin has reviewed this message.', verbose_name='Has been read?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
                ('responded_at', models.DateTimeField(blank=True, help_text='Automatically set when the message is first marked as read.', null=True, verbose_name='Responded At')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='Responded By')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
