# Generated by Django 5.2.13 on 2026-05-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("followed", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="follower_links", to="auth.user", verbose_name="Followed user")),
                ("follower", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="following_links", to="auth.user", verbose_name="Follower")),
            ],
            options={
                "verbose_name": "User follow",
                "verbose_name_plural": "User follows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="userfollow",
            constraint=models.UniqueConstraint(fields=("follower", "followed"), name="unique_user_follow_relation"),
        ),
    ]
