# Generated by Django 5.2.13 on 2026-05-11 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userfollow'),
        ('posts', '0004_postfavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('followed_author_published_post', 'Followed author published post'), ('comment_on_your_post', 'Comment on your post'), ('reply_to_your_comment', 'Reply to your comment'), ('post_favorited', 'Post favorited'), ('your_book_purchased', 'Your book purchased')], max_length=64, verbose_name='Notification type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Dedupe key')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.post', verbose_name='Related post')),
            ],
            options={
                'verbose_name': 'User notification',
                'verbose_name_plural': 'User notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='accounts_us_recipie_330704_idx'), models.Index(fields=['recipient', 'notification_type'], name='accounts_us_recipie_7e70c5_idx')],
            },
        ),
    ]
