# Generated by Django 5.2.13 on 2026-06-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profileskilltype_hierarchy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilecertification',
            options={'ordering': ['-issue_date', '-id', 'order'], 'verbose_name': 'Certification', 'verbose_name_plural': 'Certifications'},
        ),
        migrations.AlterModelOptions(
            name='profileskill',
            options={'ordering': ['skill_type__parent__order', 'skill_type__parent__slug', 'skill_type__order', 'skill_type__slug', 'id'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='profileskilltype',
            options={'ordering': ['parent__order', 'parent__slug', 'order', 'slug'], 'verbose_name': 'Skill type', 'verbose_name_plural': 'Skill types'},
        ),
    ]
