# Generated by Django 5.2.13 on 2026-09-09 21:41

from django.db import migrations, models


DEMO_PROFILES = {
    "tecnico-prl": "images/avatars/role-prl.svg",
    "trabajador": "images/avatars/role-worker.svg",
    "responsable-empresa": "images/avatars/role-management.svg",
    "responsable-mantenimiento": "images/avatars/role-maintenance.svg",
    "tecnico-calidad": "images/avatars/role-quality.svg",
    "desarrollador-sistema": "images/avatars/role-development.svg",
    "especialista-proteccion-datos": "images/avatars/role-privacy.svg",
    "profesional-autonomo": "images/avatars/role-worker.svg",
}


def migrate_demo_profiles(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    User = apps.get_model("auth", "User")
    for username, avatar_path in DEMO_PROFILES.items():
        profile = Profile.objects.filter(user__username=username).first()
        if not profile:
            continue
        profile.is_demo_commenter = True
        profile.role_avatar_path = avatar_path
        profile.is_trusted_commenter = True
        profile.save(
            update_fields=[
                "is_demo_commenter",
                "role_avatar_path",
                "is_trusted_commenter",
            ]
        )
        User.objects.filter(pk=profile.user_id).update(
            is_active=False,
            password="!demo-commenter-no-login",
        )


def reverse_demo_profiles(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    Profile.objects.filter(user__username__in=DEMO_PROFILES).update(
        is_demo_commenter=False,
        role_avatar_path="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_profileexternalpublication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_demo_commenter',
            field=models.BooleanField(default=False, help_text='Marks an editorial demonstration identity. It cannot sign in, but can receive points and participate in comment threads.', verbose_name='Is a demo commenter?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role_avatar_path',
            field=models.CharField(blank=True, help_text='Optional static asset path for a role avatar, for example images/avatars/role-prl.svg.', max_length=255, verbose_name='Role avatar path'),
        ),
        migrations.RunPython(migrate_demo_profiles, reverse_demo_profiles),
    ]
