# Generated by Django 5.2.13 on 2026-09-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_is_demo_commenter_profile_role_avatar_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('followed_author_published_post', 'Followed author published post'), ('comment_on_your_post', 'Comment on your post'), ('reply_to_your_comment', 'Reply to your comment'), ('new_follower', 'New follower'), ('post_favorited', 'Post favorited'), ('your_book_purchased', 'Your book purchased')], max_length=64, verbose_name='Notification type'),
        ),
    ]
