# Generated by Django 5.2.13 on 2026-09-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_usernotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='email_delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('skipped', 'Not sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16, verbose_name='Email delivery status'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='email_error',
            field=models.TextField(blank=True, verbose_name='Email delivery error'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email sent at'),
        ),
    ]
