# Generated by Django 5.2.13 on 2026-05-25 18:36

import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('source_notebook', models.FileField(blank=True, null=True, upload_to='notebooks/source/', verbose_name='Source notebook (.ipynb)')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notebooks', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('categories', models.ManyToManyField(blank=True, related_name='notebooks', to='categories.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Notebook',
                'verbose_name_plural': 'Notebooks',
                'ordering': ['-published_at', '-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NotebookTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
                ('abstract', models.TextField(blank=True, verbose_name='Abstract')),
                ('markdown_source', models.TextField(blank=True, help_text='Paste Markdown exported from Jupyter or written manually.', verbose_name='Markdown source')),
                ('rendered_html', models.TextField(blank=True, editable=False, help_text='Generated automatically from the Markdown source on save.', verbose_name='Rendered HTML')),
                ('trusted_html_fragment', models.TextField(blank=True, help_text='Optional self-contained HTML fragment for trusted embeds such as Plotly exports with inline JS.', verbose_name='Trusted interactive HTML')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
                ('keywords', models.CharField(blank=True, max_length=300, verbose_name='Keywords')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='notebooks.notebook')),
            ],
            options={
                'verbose_name': 'Notebook Translation',
                'db_table': 'notebooks_notebook_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master'), ('language_code', 'slug')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
