# Generated by Django 5.2.13 on 2026-09-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu_icon_class',
            field=models.CharField(blank=True, help_text='Optional Font Awesome classes, for example: fas fa-shield-alt.', max_length=100, verbose_name='Menu icon class'),
        ),
    ]
