# Generated by Django 5.2.13 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category_menu_icon_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_visible",
            field=models.BooleanField(
                default=True,
                help_text="Show this category and its associated posts in public category trees, menus, and listings.",
                verbose_name="Show",
            ),
        ),
    ]
