# Generated by Django 5.2.13 on 2026-05-10 14:58

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('click_count', models.PositiveIntegerField(db_index=True, default=0, help_text='Increases by 1 when visitors open this tag from a tag link.', verbose_name='Tag Click Score')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TagDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Daily Click Score')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='tags.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag Daily Metric',
                'verbose_name_plural': 'Tag Daily Metrics',
                'indexes': [models.Index(fields=['date'], name='tags_tagdai_date_e483ed_idx'), models.Index(fields=['tag', 'date'], name='tags_tagdai_tag_id_b55880_idx')],
                'unique_together': {('tag', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TaggedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('ca', 'Català')], default='es', help_text='Language of the post translation where this tag applies.', max_length=10, verbose_name='Language')),
                ('relevance_score', models.PositiveIntegerField(default=100, help_text='Optional score from 0 to 100 indicating tag relevance.', verbose_name='Relevance Score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='posts.post', verbose_name='Post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_links', to='tags.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tagged Post',
                'verbose_name_plural': 'Tagged Posts',
                'unique_together': {('post', 'tag', 'language')},
            },
        ),
        migrations.CreateModel(
            name='TagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('label', models.CharField(max_length=250, verbose_name='Label')),
                ('translated_slug', models.SlugField(blank=True, help_text='Optional language-specific slug. Falls back to the global slug.', max_length=250, verbose_name='Slug for this Language')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tags.tag')),
            ],
            options={
                'verbose_name': 'Tag Translation',
                'db_table': 'tags_tag_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
