# Generated by Django 5.2.13 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("free_access", "Free access granted"),
                    ("pending_payment", "Pending payment"),
                    ("payment_unavailable", "Payment unavailable"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending_payment",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
