from datetime import date

from django.contrib.contenttypes.models import ContentType
from django.core.management.base import BaseCommand, CommandError

from posts.models import Post
from sources.models import Citation, Source


POST_SLUG = "prevenir-con-pocos-recursos-reto-pymes-autonomos"


SOURCES = [
    ("Seguridad y salud en microempresas y pequeñas empresas: la perspectiva del lugar de trabajo", "Agencia Europea para la Seguridad y la Salud en el Trabajo (EU-OSHA)", "report", "en", date(2018, 1, 1), "https://osha.europa.eu/en/publications/safety-and-health-micro-and-small-enterprises-eu-view-workplace", "https://osha.europa.eu/sites/default/files/Safety_and_health_MSEs_Report_view_from_the_workplace.pdf", "Safety and health in micro and small enterprises in the EU: the view from the workplace. Walters, David; Wadsworth, Emma; Hasle, Peter; Refslund, Bjarke; Ramioul, Monique; Antonsson, Ann-Beth. EU-OSHA, Oficina de Publicaciones de la Unión Europea, Luxemburgo, 2018. Informe del proyecto SESAME, 163 pp. ISBN 978-92-9020-597-5. DOI: 10.2823/993143.", "Es la fuente principal porque estudia directamente la experiencia de propietarios y trabajadores de 162 microempresas y pequeñas empresas de nueve países europeos. Respalda las afirmaciones sobre falta de recursos, concentración de responsabilidades, gestión informal, confianza excesiva en la experiencia y tendencia a reaccionar después de que ocurra algo.", "Resumen ejecutivo (pp. 9–12); capítulos 3 (pp. 54–59), 7 (pp. 100–107), 8 (pp. 109–116), 11 (pp. 132–138) y 12 (pp. 140–149); recuadros 1 y 3; tablas 14 y 15.", "Apartados relevantes:\n• Resumen ejecutivo: metodología, características y resultados.\n• Capítulo 3: conocimiento preventivo, actuación reactiva y gestión poco sistemática.\n• Capítulos 7 y 8: transporte, restauración, presión productiva y riesgos habituales.\n• Capítulos 11 y 12: sentido común, normalización del peligro y perfiles preventivos.\n• Recuadros 1 y 3: ejemplos de microempresa y restaurante reactivo; tablas 14 y 15: diferencias por tamaño y sector.", True),
    ("Informe final del proyecto SESAME", "Agencia Europea para la Seguridad y la Salud en el Trabajo (EU-OSHA)", "report", "en", date(2018, 1, 1), "https://osha.europa.eu/en/publications", "https://osha.europa.eu/sites/default/files/Safety_and_health_MSEs_Final_report_3_yr_SESAME.pdf", "Safety and Health in Micro and Small Enterprises in the EU: Final report from the 3-year SESAME project. Walters, David; Wadsworth, Emma; Hasle, Peter; Refslund, Bjarke; Ramioul, Monique. EU-OSHA, Oficina de Publicaciones de la Unión Europea, 2018, 103 pp. ISBN 978-92-9496-894-4. DOI: 10.2802/29855.", "Complementa el informe principal y respalda que las soluciones para pymes no deben limitarse a reducir formularios: deben ser fáciles de aplicar, sostenibles, adaptadas al sector y acompañadas.", "Resumen ejecutivo (pp. 7–12); apartado 2.2 (desde p. 22); capítulo 5 (pp. 64–83); apartado 6.4 (pp. 89–92); pp. 12 y 81–82.", "Analiza barreras estructurales, la relación entre tamaño y prevención, qué soluciones funcionan y la necesidad de apoyos sencillos, transferibles y adaptados al sector.", False),
    ("Retrato de la PYME. DIRCE a 1 de enero de 2024", "Dirección General de Estrategia Industrial y de la Pequeña y Mediana Empresa; Ministerio de Industria y Turismo", "report", "es", date(2026, 5, 1), "https://ipyme.org/Publicaciones/Retrato%20de%20la%20PYME/Retrato_Pyme_DIRCE_2024.pdf", "https://ipyme.org/Publicaciones/Retrato%20de%20la%20PYME/Retrato_Pyme_DIRCE_2024.pdf", "Retrato de la PYME. DIRCE a 1 de enero de 2024. Dirección General de Estrategia Industrial y de la Pequeña y Mediana Empresa, Ministerio de Industria y Turismo, mayo de 2026. Fuente estadística: INE, DIRCE. ISSN 2792-9647. NIPO 217-24-012-8.", "Demuestra que las pymes y los negocios sin asalariados no son casos marginales, sino la estructura predominante del tejido empresarial español.", "Páginas 3–5: apartado Empresas en España; tabla 1; apartado Sectores y tablas 2, 3 y 4.", "La tabla 1 cifra en 3.250.210 las pymes, equivalentes al 99,8 % de las empresas, y recoge 1.692.479 pymes sin asalariados. Las tablas posteriores sitúan las diferencias por sector.", False),
    ("Ley 31/1995, de 8 de noviembre, de Prevención de Riesgos Laborales", "Jefatura del Estado; Boletín Oficial del Estado", "law", "es", date(1995, 11, 8), "https://www.boe.es/buscar/act.php?id=BOE-A-1995-24292", "", "Ley 31/1995, de 8 de noviembre, de Prevención de Riesgos Laborales. BOE núm. 269, de 10 de noviembre de 1995. Referencia BOE-A-1995-24292. Texto consolidado.", "Fundamenta que simplificar la gestión preventiva no significa reducir la protección y que la prevención debe integrarse en la actividad de la empresa y mantenerse bajo seguimiento.", "Arts. 5.5, 14, 15, 16, 18, 23 y 30; disposición adicional decimoséptima.", "Incluye integración preventiva, evaluación y planificación, información y participación, documentación, modalidades de organización y asesoramiento para empresas de hasta 25 trabajadores.", False),
    ("Real Decreto 39/1997, de 17 de enero, Reglamento de los Servicios de Prevención", "Ministerio de Trabajo y Asuntos Sociales; Boletín Oficial del Estado", "law", "es", date(1997, 1, 17), "https://www.boe.es/buscar/act.php?id=BOE-A-1997-1853", "", "Real Decreto 39/1997, de 17 de enero, por el que se aprueba el Reglamento de los Servicios de Prevención. BOE núm. 27, de 31 de enero de 1997. Referencia BOE-A-1997-1853. Texto consolidado.", "Explica que una pyme puede usar documentación más sencilla, pero debe conservar evaluación, medidas, responsables, recursos, plazos y seguimiento; la simplificación no equivale a improvisación.", "Arts. 1–11, especialmente 2.2, 2.4, 3, 4.3, 5, 7, 8 y 9.", "Regula la integración, la adaptación del plan al tamaño, la evaluación competente, los medios y plazos de planificación y las modalidades preventivas.", False),
    ("Ley 20/2007, de 11 de julio, del Estatuto del trabajo autónomo", "Jefatura del Estado; Boletín Oficial del Estado", "law", "es", date(2007, 7, 11), "https://www.boe.es/buscar/act.php?id=BOE-A-2007-13409", "", "Ley 20/2007, de 11 de julio, del Estatuto del trabajo autónomo. BOE núm. 166, de 12 de julio de 2007. Referencia BOE-A-2007-13409.", "Respalda el caso del autónomo y evita confundir al autónomo sin personal, al autónomo concurrente y al autónomo que también actúa como empresario.", "Art. 8, Prevención de riesgos laborales; apartados 1–8.", "Incluye asesoramiento, formación adaptada, cooperación en concurrencia, deberes de la empresa contratante, equipos de terceros, interrupción ante riesgo grave y obligaciones cuando hay personal contratado.", False),
    ("Real Decreto 171/2004, de 30 de enero, sobre coordinación de actividades empresariales", "Ministerio de Trabajo y Asuntos Sociales; Boletín Oficial del Estado", "law", "es", date(2004, 1, 30), "https://www.boe.es/buscar/act.php?id=BOE-A-2004-1848", "", "Real Decreto 171/2004, de 30 de enero, por el que se desarrolla el artículo 24 de la Ley 31/1995, en materia de coordinación de actividades empresariales. BOE núm. 27, de 31 de enero de 2004. Referencia BOE-A-2004-1848.", "Fundamenta los casos en los que una pequeña empresa o una persona autónoma trabaja en instalaciones ajenas y la necesidad de distinguir los distintos deberes de coordinación.", "Arts. 4, 5, 7–13, especialmente 4.1–4.3, 9.4 y 10.", "Trata cooperación e intercambio de información, emergencias, medios de coordinación, información e instrucciones del titular, vigilancia de la empresa principal y actualización de medidas.", False),
    ("Prevención10.es: asesoramiento público para pymes y autónomos", "Instituto Nacional de Seguridad y Salud en el Trabajo (INSST)", "official_guidance", "es", None, "https://www.insst.es/el-instituto/conoce-el-instituto/servicios-del-instituto/asesoramiento-publico", "", "Servicios del Instituto: Prevención10.es. Instituto Nacional de Seguridad y Salud en el Trabajo, Ministerio de Trabajo y Economía Social. Página institucional consultada el 11 de septiembre de 2026.", "Demuestra que las instituciones públicas españolas ya han reconocido la necesidad de herramientas sencillas y acompañamiento práctico para pymes y autónomos.", "Apartado «Prevención10.es — Asesoramiento público en materia de prevención de riesgos laborales para pymes y autónomos».", "Servicio público gratuito que ofrece gestión simplificada para empresas de hasta 25 personas trabajadoras, apoyo a autónomos sin personal, coordinación, información práctica y cultura preventiva.", False),
]


class Command(BaseCommand):
    help = "Importa las fuentes verificadas del post sobre pymes y autónomos."

    def handle(self, *args, **options):
        post = Post.objects.filter(translations__slug=POST_SLUG).distinct().first()
        if post is None:
            raise CommandError(f"No existe el post con slug '{POST_SLUG}'.")
        content_type = ContentType.objects.get_for_model(Post, for_concrete_model=False)
        for order, data in enumerate(SOURCES, start=1):
            title, organisation, source_type, language, published, url, document_url, reference, summary, locator, note, primary = data
            source = Source.objects.filter(translations__title=title).distinct().first() or Source()
            source.organisation, source.source_type, source.language = organisation, source_type, language
            source.publication_date, source.url, source.document_url = published, url, document_url
            source.status = Source.Status.VERIFIED
            source.set_current_language("es")
            source.title, source.bibliographic_reference, source.summary = title, reference, summary
            source.save()
            Citation.objects.update_or_create(
                source=source, content_type=content_type, object_id=post.pk, language="es",
                defaults={"is_primary": primary, "order": order, "locator": locator, "note": note},
            )
        self.stdout.write(self.style.SUCCESS(f"{len(SOURCES)} fuentes verificadas vinculadas a '{post}'."))
