# Generated by Django 5.2.13 on 2026-05-10 14:58

import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(blank=True, max_length=100, null=True, verbose_name='DOI')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='publications/files/', verbose_name='Full PDF')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, verbose_name='Publication Date')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('authors', models.ManyToManyField(related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Authors')),
                ('categories', models.ManyToManyField(blank=True, related_name='publications', to='categories.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-publication_date'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PublicationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(help_text='Recommended length: 5–15 words.', max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
                ('abstract', tinymce.models.HTMLField(blank=True, help_text='Summarize objectives, methods, and key findings. Recommended length: 150–250 words.', verbose_name='Abstract')),
                ('introduction', tinymce.models.HTMLField(blank=True, help_text='Contextualize the problem, justify the study, and introduce the research topic. Recommended length: 300–800 words.', verbose_name='Introduction')),
                ('theoretical_framework', tinymce.models.HTMLField(blank=True, help_text='Develop the conceptual foundation, key authors, theories, and relevant prior work. Recommended length: 500–1000 words.', verbose_name='Theoretical framework')),
                ('objectives_hypotheses', tinymce.models.HTMLField(blank=True, help_text='Define research questions, objectives, and hypotheses. Recommended length: 100–200 words.', verbose_name='Objectives and hypotheses')),
                ('methodology', tinymce.models.HTMLField(blank=True, help_text='Describe the research design, sample, instruments, data collection, and analysis techniques. Recommended length: 300–600 words.', verbose_name='Methodology')),
                ('results', tinymce.models.HTMLField(blank=True, help_text='Present findings, data, tables, figures, categories, or statistical results. Recommended length: 300–700 words.', verbose_name='Results')),
                ('discussion', tinymce.models.HTMLField(blank=True, help_text='Interpret findings, compare them with the literature, and discuss implications and limitations. Recommended length: 400–800 words.', verbose_name='Discussion')),
                ('conclusions', tinymce.models.HTMLField(blank=True, help_text='Answer the research questions and highlight the main contributions. Recommended length: 100–200 words.', verbose_name='Conclusions')),
                ('references', tinymce.models.HTMLField(blank=True, help_text='List all cited sources, books, academic articles, reports, DOI links, or URLs. Recommended: 5–20 sources when applicable.', verbose_name='References / Bibliography')),
                ('annexes', tinymce.models.HTMLField(blank=True, help_text='Optional supplementary material such as questionnaires, raw data, transcripts, or software used.', verbose_name='Annexes')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
                ('featured_image_asset', models.ForeignKey(blank=True, help_text='Primary publication cover image from Media Library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Featured image (library)')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='publications.publication')),
                ('social_image_asset', models.ForeignKey(blank=True, help_text='Square or social-preview image from Media Library, used near the abstract and in cards/previews.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Social image (library)')),
            ],
            options={
                'verbose_name': 'Publication Translation',
                'db_table': 'publications_publication_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
