# Generated by Codex on 2026-05-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationtranslation",
            name="mobile_image_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Vertical 9:16 image from Media Library for mobile-first widgets or layouts.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="gallery.image",
                verbose_name="Mobile image (library)",
            ),
        ),
    ]
