# Generated by Django 5.2.13 on 2026-05-10 14:58

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Zone Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (used in templates)')),
            ],
            options={
                'verbose_name': 'Widget Zone',
                'verbose_name_plural': 'Widget Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('recent_posts', 'Recent Blog Posts'), ('most_viewed_posts', 'Most Viewed Blog Posts'), ('most_commented_posts', 'Most Commented Blog Posts'), ('blog_categories', 'Blog Category List'), ('featured_tags', 'Featured Tags'), ('editor_picks_posts', "Editor's Picks (Blog Posts)"), ('post_grid_recent', 'Post Grid: Recent Posts'), ('post_grid_category', 'Post Grid: Category'), ('post_grid_popular', 'Post Grid: Most Viewed'), ('post_grid_commented', 'Post Grid: Most Commented'), ('post_grid_editor', "Post Grid: Editor's Picks"), ('post_intent_reflection', 'Intent: For Reflection'), ('post_intent_quick_reads', 'Intent: Quick Reads'), ('post_intent_wellbeing', 'Intent: Well-being'), ('post_intent_debate', 'Intent: Debate Starters'), ('post_carousel', 'Post Carousel'), ('post_carousel_commented', 'Post Carousel: Most Commented'), ('post_carousel_viewed', 'Post Carousel: Most Viewed'), ('user_directory', 'User Directory'), ('testimonials', 'Testimonials')], max_length=50, verbose_name='Widget Type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('item_count', models.PositiveIntegerField(default=5, help_text="Used by widgets that display a list of items, like 'Recent Posts' or 'Blog Categories'.", verbose_name='Number of items to show')),
                ('cache_timeout', models.PositiveIntegerField(default=900, help_text='How long the results of this widget should be stored in cache. 0 to disable caching for this widget.', verbose_name='Cache Timeout (in seconds)')),
                ('column_count', models.PositiveIntegerField(default=3, help_text='Number of columns for grid display (e.g., 2, 3, 4).', verbose_name='Column Count')),
                ('view_all_link_url', models.CharField(blank=True, help_text="URL for the 'View All' link (e.g., '/blog/').", max_length=255, null=True, verbose_name='View All Link URL')),
                ('carousel_interval_ms', models.PositiveIntegerField(default=5000, help_text="Time in milliseconds between slides for 'Post Carousel' widget.", verbose_name='Carousel Interval (ms)')),
                ('category_filter', models.ForeignKey(blank=True, help_text='If selected, the widget will only show items from this specific category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='Filter by Category (optional)')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='widgets.widgetzone', verbose_name='Widget Zone')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['zone', 'order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WidgetTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(help_text='The title that will be displayed above the widget.', max_length=100, verbose_name='Widget Title')),
                ('section_title', models.CharField(blank=True, help_text="A main title for this grid section (e.g., 'Latest Posts', 'Our Bestsellers').", max_length=200, null=True, verbose_name='Section Title (Optional)')),
                ('view_all_link_text', models.CharField(blank=True, help_text="Text for the 'View All' link below the grid (e.g., 'View All Posts').", max_length=100, null=True, verbose_name='View All Link Text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='widgets.widget')),
            ],
            options={
                'verbose_name': 'Widget Translation',
                'db_table': 'widgets_widget_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
