# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0005_alter_widget_widget_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="image_format",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("square", "Square / Social"),
                    ("landscape", "Landscape / Featured"),
                ],
                default="auto",
                help_text="Controls whether widgets should prefer square/social or landscape/featured images.",
                max_length=20,
                verbose_name="Image Format",
            ),
        ),
    ]
