# Generated by Django 5.2.13 on 2026-05-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0007_alter_widget_image_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='image_format',
            field=models.CharField(choices=[('auto', 'Auto'), ('square', 'Square / Social'), ('landscape', 'Landscape / Featured'), ('mobile', 'Mobile / 9:16')], default='auto', help_text='Choose which visual format this widget should prefer: landscape, square/social, or mobile 9:16.', max_length=20, verbose_name='Image Format'),
        ),
    ]
