# Generated by Django 5.2.13 on 2026-05-10 14:58

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_items_per_page', models.PositiveIntegerField(default=9, help_text='Number of posts to show on the main blog page and on category pages.', verbose_name='Items per Page in Blog/Category lists')),
                ('search_pages_per_page', models.PositiveIntegerField(default=5, verbose_name='Pages per Page in Search Results')),
                ('search_posts_per_page', models.PositiveIntegerField(default=5, verbose_name='Posts per Page in Search Results')),
                ('search_results_per_page', models.PositiveIntegerField(default=5, help_text='Number of items to show per section (Pages/Posts) on the search results page.', verbose_name='Results per Page in Search')),
                ('search_importance_limit', models.PositiveIntegerField(default=3, help_text='How many top-priority pages to display before regular search results.', verbose_name="Number of 'Important' Pages to show first in search")),
                ('comment_indentation_pixels', models.PositiveIntegerField(default=20, help_text='Controls the visual indentation for nested comments in the admin.', verbose_name='Comment Indentation (in pixels)')),
                ('auto_approve_comments', models.BooleanField(default=False, help_text='If checked, new comments will be published immediately without moderation.', verbose_name='Auto-approve comments')),
                ('menu_cache_timeout', models.PositiveIntegerField(default=3600, help_text='How long the site menus should be stored in cache. Set to 0 to disable menu caching (not recommended).', verbose_name='Menu Cache Timeout (in seconds)')),
                ('trusted_commenter_threshold', models.PositiveIntegerField(default=3, help_text='The number of approved comments a user needs to post before their future comments are auto-approved.', verbose_name='Trusted Commenter Threshold')),
                ('category_tree_cache_timeout', models.PositiveIntegerField(default=43200, help_text='How long the full category tree should be stored in cache. High values are recommended.', verbose_name='Category Tree Cache Timeout (in seconds)')),
                ('gallery_items_per_page', models.PositiveIntegerField(default=9, help_text='Number of images to show on the image gallery page.', verbose_name='Items per Page in Gallery')),
                ('user_profile_items_per_page', models.PositiveIntegerField(default=5, help_text="Number of posts/comments to show per page on a user's public profile.", verbose_name='Items per Page on Public Profile')),
                ('user_directory_items_per_page', models.PositiveIntegerField(default=25, help_text='Number of users listed per page on the public user directory.', verbose_name='Items per Page in User Directory')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='SiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Template Name')),
                ('chosen', models.BooleanField(db_index=True, default=False, verbose_name='Chosen')),
                ('site_logo', models.ImageField(blank=True, help_text='The main logo displayed in the top bar.', null=True, upload_to='site_branding/', verbose_name='Site Logo')),
                ('favicon', models.ImageField(blank=True, help_text='Small icon used by browser tabs, bookmarks, and shortcuts.', null=True, upload_to='site_branding/favicons/', verbose_name='Favicon')),
                ('top_bar_banner_image', models.ImageField(blank=True, help_text='An optional banner image displayed in the top bar.', null=True, upload_to='site_branding/banners/', verbose_name='Top Bar Banner Image')),
                ('top_bar_banner_link', models.URLField(blank=True, help_text='The URL the banner image will link to.', max_length=255, verbose_name='Top Bar Banner Link')),
                ('primary_color', models.CharField(default='#ffc107', max_length=7, verbose_name='Primary Color')),
                ('dark_color', models.CharField(default='#212529', max_length=7, verbose_name='Dark Color')),
                ('light_color', models.CharField(default='#f8f9fa', max_length=7, verbose_name='Light Color')),
                ('body_background_color', models.CharField(default='#f8f9fa', max_length=7, verbose_name='Body Background Color')),
                ('body_text_color', models.CharField(default='#212529', max_length=7, verbose_name='Body Text Color')),
                ('card_box_background_color', models.CharField(default='#f1f3f5', max_length=7, verbose_name='Card Box Background Color')),
                ('card_box_border_color', models.CharField(default='#dee2e6', max_length=7, verbose_name='Card Box Border Color')),
                ('home_notice_background_color', models.CharField(default='#eef2f5', max_length=7, verbose_name='Home Notice Background Color')),
                ('home_notice_text_color', models.CharField(default='#495057', max_length=7, verbose_name='Home Notice Text Color')),
                ('font_family', models.CharField(default="system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", max_length=160, verbose_name='Font Family')),
                ('base_font_size', models.PositiveIntegerField(default=16, verbose_name='Base Font Size')),
                ('slogan_font_size', models.PositiveIntegerField(default=28, verbose_name='Slogan Font Size')),
                ('logo_height', models.PositiveIntegerField(default=50, verbose_name='Logo Height')),
                ('banner_max_height', models.PositiveIntegerField(default=50, verbose_name='Banner Max Height')),
                ('border_radius', models.PositiveIntegerField(default=4, verbose_name='Border Radius')),
                ('layout_max_width', models.PositiveIntegerField(default=1440, verbose_name='Layout Max Width')),
                ('layout_horizontal_padding', models.PositiveIntegerField(default=16, verbose_name='Layout Horizontal Padding')),
                ('content_width_percent', models.PositiveIntegerField(default=64, verbose_name='Content Width Percent')),
                ('left_sidebar_width_percent', models.PositiveIntegerField(default=18, verbose_name='Left Sidebar Width Percent')),
                ('right_sidebar_width_percent', models.PositiveIntegerField(default=18, verbose_name='Right Sidebar Width Percent')),
                ('category_tree_max_width', models.PositiveIntegerField(default=860, verbose_name='Category Tree Max Width')),
                ('category_tree_background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Category Tree Background Color')),
                ('category_tree_border_color', models.CharField(default='#dee2e6', max_length=7, verbose_name='Category Tree Border Color')),
                ('category_tree_base_padding', models.PositiveIntegerField(default=8, verbose_name='Category Tree Base Padding')),
                ('category_tree_indent_step', models.PositiveIntegerField(default=24, verbose_name='Category Tree Indent Step')),
                ('category_tree_row_padding_y', models.PositiveIntegerField(default=8, verbose_name='Category Tree Row Vertical Padding')),
            ],
            options={
                'verbose_name': 'Site Template',
                'verbose_name_plural': 'Site Templates',
                'db_table': 'site_settings_templates',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteTemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('site_slogan', models.CharField(blank=True, help_text='A short tagline displayed next to the logo.', max_length=150, verbose_name='Site Slogan')),
                ('footer_copyright_text', models.TextField(blank=True, help_text='Optional footer copyright text. Use {year} where the current year should appear.', verbose_name='Footer Copyright Text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='site_settings.sitetemplate')),
            ],
            options={
                'verbose_name': 'Site Template Translation',
                'db_table': 'site_settings_templates_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
