# Generated by Django 5.2.13 on 2026-05-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='daily_post_points_budget',
            field=models.PositiveIntegerField(default=10, help_text='How many points each authenticated user can distribute across posts per day.', verbose_name='Daily post points budget'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='max_points_per_post_per_day',
            field=models.PositiveIntegerField(default=5, help_text='Upper limit a user can assign to a single post within the same day.', verbose_name='Max points per post per day'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='post_points_enabled',
            field=models.BooleanField(default=True, help_text='Allows authenticated users to distribute a limited number of points to posts each day.', verbose_name='Enable post points'),
        ),
    ]
