# Generated by Django 5.2.13 on 2026-05-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0002_siteconfiguration_daily_post_points_budget_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="allow_author_self_points",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, authors may spend their daily points on their own published posts.",
                verbose_name="Allow authors to rate their own posts",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="post_points_min_account_age_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of days a user account must exist before it can assign points to posts. Use 0 to disable this restriction.",
                verbose_name="Minimum account age for post points",
            ),
        ),
    ]
