# Generated by Codex on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0003_siteconfiguration_allow_author_self_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitetemplate",
            name="navigation_banner_height",
            field=models.PositiveIntegerField(
                default=36,
                help_text="Displayed height in pixels for the compact banner beside the shopping cart.",
                verbose_name="Navigation Banner Height",
            ),
        ),
        migrations.AddField(
            model_name="sitetemplate",
            name="navigation_banner_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional compact image displayed immediately before the shopping cart.",
                null=True,
                upload_to="site_branding/navigation/",
                verbose_name="Navigation Banner Image",
            ),
        ),
        migrations.AddField(
            model_name="sitetemplate",
            name="navigation_banner_link",
            field=models.URLField(
                blank=True,
                help_text="Destination URL when the navigation banner is clicked.",
                max_length=255,
                verbose_name="Navigation Banner Link",
            ),
        ),
    ]
