# Generated by Django 5.2.13 on 2026-09-11 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_image_image'),
        ('site_settings', '0004_sitetemplate_navigation_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplate',
            name='favicon_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Favicon (media library)'),
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='navigation_banner_image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Navigation banner (media library)'),
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='site_logo_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Site logo (media library)'),
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='top_bar_banner_image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Top bar banner (media library)'),
        ),
    ]
