# Generated by Django 5.2.13 on 2026-09-11 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_sitetemplate_favicon_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='homepage_post_grid_columns',
            field=models.PositiveSmallIntegerField(default=2, help_text='Desktop columns in the latest-posts grid on the homepage.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Homepage post grid columns'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='homepage_post_grid_rows',
            field=models.PositiveSmallIntegerField(default=3, help_text='Rows shown before homepage post pagination. Posts per page are rows × columns.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Homepage post grid rows'),
        ),
    ]
