# Generated by Django 5.2.13 on 2026-09-13

from django.db import migrations, models


def update_default_template_colors(apps, schema_editor):
    SiteTemplate = apps.get_model("site_settings", "SiteTemplate")
    SiteTemplate.objects.filter(name="Default").update(
        primary_color="#F8D454",
        dark_color="#3776AB",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0006_siteconfiguration_homepage_post_grid_columns_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitetemplate",
            name="primary_color",
            field=models.CharField(default="#F8D454", max_length=7, verbose_name="Primary Color"),
        ),
        migrations.AlterField(
            model_name="sitetemplate",
            name="dark_color",
            field=models.CharField(default="#3776AB", max_length=7, verbose_name="Dark Color"),
        ),
        migrations.RunPython(update_default_template_colors, migrations.RunPython.noop),
    ]
