# Generated by Django 5.2.13 on 2026-09-13

from django.db import migrations, models


def update_default_template_dark_color(apps, schema_editor):
    SiteTemplate = apps.get_model("site_settings", "SiteTemplate")
    SiteTemplate.objects.filter(name="Default").update(dark_color="#003399")


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0007_default_bee_python_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitetemplate",
            name="dark_color",
            field=models.CharField(default="#003399", max_length=7, verbose_name="Dark Color"),
        ),
        migrations.RunPython(update_default_template_dark_color, migrations.RunPython.noop),
    ]
