# Generated by Django 5.2.13 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0008_default_bee_python_dark_blue"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitetemplate",
            name="main_navigation_background_color",
            field=models.CharField(
                default="#003399",
                help_text="Background color of the upper navigation menu.",
                max_length=7,
                verbose_name="Main navigation background color",
            ),
        ),
        migrations.AddField(
            model_name="sitetemplate",
            name="category_navigation_background_color",
            field=models.CharField(
                default="#1B262B",
                help_text="Background color of the category navigation menu.",
                max_length=7,
                verbose_name="Category navigation background color",
            ),
        ),
    ]
