# Generated by Django 5.2.13 on 2026-09-13 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_image_image'),
        ('site_settings', '0009_sitetemplate_navigation_background_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetemplate',
            name='digital_beeb_system_icon_asset',
            field=models.ForeignKey(blank=True, help_text='Icon shown beside the Digital BeeB category in the category navigation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.image', verbose_name='Digital BeeB system icon (media library)'),
        ),
    ]
