# Generated by Django 5.2.13 on 2026-05-10 14:58

import django.db.models.deletion
import mptt.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('categories', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('link_type', models.CharField(choices=[('url', 'Manual URL'), ('home', 'Home Page'), ('page', 'Single Page'), ('category', 'Single Category'), ('post_list', 'Post List (Dropdown)'), ('all_blog_categories', 'Post Categories Tree (Dropdown)'), ('important_pages', 'Important Pages List (Dropdown)')], default='url', help_text='Determines how this menu item behaves: a direct link, or a dynamic content generator.', max_length=50, verbose_name='Link Type')),
                ('link_url', models.CharField(blank=True, help_text="Use for external URLs (e.g., 'https://google.com') or custom internal paths (e.g., '/blog/'). Only used if Link Type is 'Manual URL'.", max_length=255, verbose_name='Manual URL')),
                ('post_list_type', models.CharField(blank=True, choices=[('latest', 'Latest Posts'), ('new', 'New Posts Today'), ('most_discussed', 'Most Discussed Posts'), ('trending', 'Trending Posts'), ('recommended', 'Recommended Posts')], help_text="Determines which posts are shown when Link Type is 'Post List'.", max_length=50, verbose_name='Post List Type')),
                ('dynamic_items_limit', models.PositiveIntegerField(default=5, help_text='Maximum number of generated items for dynamic dropdowns.', verbose_name='Dynamic Items Limit')),
                ('icon_class', models.CharField(blank=True, help_text="FontAwesome class (e.g., 'fas fa-home') to display an icon next to the link.", max_length=100, verbose_name='Icon Class')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Leave empty to show this menu item to everyone. Select one or more groups to restrict visibility.', related_name='visible_menu_items', to='auth.group', verbose_name='Visible for groups')),
                ('link_category', models.ForeignKey(blank=True, help_text="Link to a specific category. Only used if Link Type is 'Single Category'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='Category Link')),
                ('link_page', models.ForeignKey(blank=True, help_text="Link to a specific internal page. Only used if Link Type is 'Single Page'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.page', verbose_name='Page Link')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menu', verbose_name='Menu')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Select a parent item to nest this menu item within it.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.menuitem', verbose_name='Parent Menu Item')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['menu', 'tree_id', 'lft', 'order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MenuItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Link Text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='menus.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Translation',
                'db_table': 'menus_menuitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MenuTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Menu Title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='menus.menu')),
            ],
            options={
                'verbose_name': 'Menu Translation',
                'db_table': 'menus_menu_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master'), ('language_code', 'title')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
