# Generated by Django 5.2.13 on 2026-05-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link_type',
            field=models.CharField(choices=[('url', 'Manual URL'), ('home', 'Home Page'), ('page', 'Single Page'), ('notebook_list', 'Notebook List'), ('category', 'Single Category'), ('post_list', 'Post List (Dropdown)'), ('all_blog_categories', 'Post Categories Tree (Dropdown)'), ('important_pages', 'Important Pages List (Dropdown)')], default='url', help_text='Determines how this menu item behaves: a direct link, or a dynamic content generator.', max_length=50, verbose_name='Link Type'),
        ),
    ]
