# Generated by Django 6.0.8 on 2026-08-15 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='instagram', max_length=30)),
                ('platform_comment_id', models.CharField(max_length=128, unique=True)),
                ('media_id', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('drafted', 'Borrador generado'), ('approved', 'Aprobado'), ('published', 'Publicado'), ('ignored', 'Ignorado'), ('error', 'Error')], default='received', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform_created_at', models.DateTimeField(blank=True, null=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='fans.fan')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('risk_level', models.CharField(default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('approved', 'Aprobado'), ('published', 'Publicado'), ('rejected', 'Rechazado')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='social.comment')),
            ],
        ),
    ]
