# Generated by Django 5.2.13 on 2026-08-15 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fans', '0001_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='instagram', max_length=30)),
                ('platform_message_id', models.CharField(max_length=160, unique=True)),
                ('recipient_platform_id', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('drafted', 'Borrador generado'), ('sent', 'Enviado'), ('ignored', 'Ignorado'), ('error', 'Error')], default='received', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform_created_at', models.DateTimeField(blank=True, null=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_messages', to='fans.fan')),
            ],
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('risk_level', models.CharField(default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado'), ('failed', 'Error de envío')], default='draft', max_length=20)),
                ('platform_message_id', models.CharField(blank=True, max_length=160)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.directmessage')),
            ],
        ),
    ]
