# Generated by Django 5.2.13 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0004_source_legacy_columns_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="document_url",
            field=models.URLField(
                blank=True,
                help_text="Optional direct link to the PDF or other original document. Keep the official landing page in Official URL.",
                verbose_name="Direct document URL",
            ),
        ),
        migrations.AddField(
            model_name="citation",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Mark the source that provides the main evidence for this content.",
                verbose_name="Primary source",
            ),
        ),
    ]
