# Generated by Django 5.2.13 on 2026-09-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_source_document_url_citation_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='note',
            field=models.TextField(blank=True, help_text='Optional explanation of how this source supports this content, including relevant sections or pages. It is shown in a collapsible panel.', verbose_name='Editorial note'),
        ),
        migrations.AlterField(
            model_name='sourcetranslation',
            name='bibliographic_reference',
            field=models.TextField(blank=True, help_text='Full reference: original title, authors, editor, place, year, ISBN/ISSN/DOI and other permanent identification data.', verbose_name='Bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='sourcetranslation',
            name='summary',
            field=models.TextField(blank=True, help_text='Explain the value of this source. It is shown to readers in a collapsible panel.', verbose_name='Source description'),
        ),
    ]
