# Generated by Django 5.2.13 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0006_alter_citation_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="context",
            field=models.TextField(
                blank=True,
                help_text="Explain the specific situation, question or section of this post, page or publication in which the source is used.",
                verbose_name="Context in this content",
            ),
        ),
        migrations.AlterField(
            model_name="citation",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Explain how this source supports this specific content, including the relevant sections or pages. It is shown in a collapsible panel.",
                verbose_name="Relevance for this content",
            ),
        ),
    ]
