# Generated by Django 6.0.8 on 2026-08-15 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='instagram', max_length=30)),
                ('platform_user_id', models.CharField(max_length=128)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('display_name', models.CharField(blank=True, max_length=180)),
                ('profile_type', models.CharField(choices=[('general', 'General'), ('vip', 'VIP'), ('special', 'Especial')], default='general', max_length=20)),
                ('is_vip', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform', 'platform_user_id'), name='unique_platform_fan')],
            },
        ),
        migrations.CreateModel(
            name='FanRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(blank=True, max_length=255)),
                ('preferred_names', models.CharField(blank=True, max_length=255)),
                ('emojis', models.CharField(blank=True, max_length=255)),
                ('forbidden_topics', models.TextField(blank=True)),
                ('special_context', models.TextField(blank=True)),
                ('human_review_required', models.BooleanField(default=False)),
                ('fan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='fans.fan')),
            ],
        ),
    ]
